// i18n.js — Shared translations for backend messages (errors, emails)
// Usage: const { t, getLang } = require('../i18n');
//        const lang = getLang(req);
//        res.json({ ok: false, err: t(lang, 'err.not_connected') });

const MESSAGES = {

  /* ── Generic errors ──────────────────────────────────────── */
  'err.not_connected': {
    fr: 'Non connecté',
    en: 'Not connected',
    de: 'Nicht verbunden',
  },
  'err.access_denied': {
    fr: 'Accès refusé',
    en: 'Access denied',
    de: 'Zugriff verweigert',
  },
  'err.access_denied_sa': {
    fr: 'Accès refusé — réservé au Super Admin',
    en: 'Access denied — Super Admin only',
    de: 'Zugriff verweigert — nur Super Admin',
  },
  'err.unknown_action': {
    fr: 'Action inconnue',
    en: 'Unknown action',
    de: 'Unbekannte Aktion',
  },

  /* ── Auth ────────────────────────────────────────────────── */
  'auth.bad_credentials': {
    fr: 'Identifiant ou mot de passe incorrect',
    en: 'Incorrect username or password',
    de: 'Benutzername oder Passwort falsch',
  },

  /* ── Admin / user management ────────────────────────────── */
  'admin.invalid_data': {
    fr: 'Données invalides (mdp min 6 car.)',
    en: 'Invalid data (password min. 6 chars)',
    de: 'Ungültige Daten (Passwort mind. 6 Zeichen)',
  },
  'admin.invalid_data_short': {
    fr: 'Données invalides',
    en: 'Invalid data',
    de: 'Ungültige Daten',
  },
  'admin.username_exists': {
    fr: "L'identifiant '{u}' existe déjà",
    en: "Username '{u}' already exists",
    de: "Benutzername '{u}' existiert bereits",
  },
  'admin.cannot_delete_self': {
    fr: 'Impossible de se supprimer soi-même',
    en: 'Cannot delete your own account',
    de: 'Eigenes Konto kann nicht gelöscht werden',
  },

  /* ── Profile ─────────────────────────────────────────────── */
  'profile.name_too_short': {
    fr: 'Nom trop court',
    en: 'Name too short',
    de: 'Name zu kurz',
  },
  'profile.pwd_too_short': {
    fr: 'Nouveau mot de passe trop court (min 6 car.)',
    en: 'New password too short (min. 6 chars)',
    de: 'Neues Passwort zu kurz (mind. 6 Zeichen)',
  },
  'profile.pwd_wrong': {
    fr: 'Mot de passe actuel incorrect',
    en: 'Current password is incorrect',
    de: 'Aktuelles Passwort ist falsch',
  },
  'profile.unknown_action': {
    fr: 'Action inconnue',
    en: 'Unknown action',
    de: 'Unbekannte Aktion',
  },

  /* ── Email (save.js — NA notification) ──────────────────── */
  'email.subject': {
    fr: '[LPA NA] Action requise — LPA{lv} Q{q} — {date}',
    en: '[LPA NA] Action required — LPA{lv} Q{q} — {date}',
    de: '[LPA NA] Aktion erforderlich — LPA{lv} F{q} — {date}',
  },
  'email.title': {
    fr: '⚠️ Point d\'audit Non Applicable — Action requise',
    en: '⚠️ Audit Point Not Applicable — Action Required',
    de: '⚠️ Auditpunkt Nicht Anwendbar — Aktion Erforderlich',
  },
  'email.subtitle': {
    fr: 'LPA Hirschmann Automotive Oujda',
    en: 'LPA Hirschmann Automotive Oujda',
    de: 'LPA Hirschmann Automotive Oujda',
  },
  'email.audit_details': {
    fr: 'Détails de l\'audit',
    en: 'Audit details',
    de: 'Audit-Details',
  },
  'email.field.auditor': {
    fr: 'Auditeur',
    en: 'Auditor',
    de: 'Auditor',
  },
  'email.field.level': {
    fr: 'Niveau',
    en: 'Level',
    de: 'Ebene',
  },
  'email.field.zone': {
    fr: 'Zone',
    en: 'Zone',
    de: 'Zone',
  },
  'email.field.date': {
    fr: 'Date audit',
    en: 'Audit date',
    de: 'Auditdatum',
  },
  'email.field.assigned': {
    fr: 'Assigné à',
    en: 'Assigned to',
    de: 'Zugewiesen an',
  },
  'email.field.specialite': {
    fr: 'Spécialité',
    en: 'Speciality',
    de: 'Spezialität',
  },
  'email.question_label': {
    fr: 'Question {n} — Réponse :',
    en: 'Question {n} — Answer:',
    de: 'Frage {n} — Antwort:',
  },
  'email.na_badge': {
    fr: 'NA',
    en: 'NA',
    de: 'NA',
  },
  'email.observation_title': {
    fr: 'Observation de l\'auditeur',
    en: 'Auditor observation',
    de: 'Beobachtung des Auditors',
  },
  'email.photo_title': {
    fr: 'Photo jointe',
    en: 'Attached photo',
    de: 'Angehängtes Foto',
  },
  'email.footer': {
    fr: 'Cet email a été généré automatiquement par le système LPA — Hirschmann Automotive Oujda',
    en: 'This email was automatically generated by the LPA system — Hirschmann Automotive Oujda',
    de: 'Diese E-Mail wurde automatisch vom LPA-System generiert — Hirschmann Automotive Oujda',
  },
};

/**
 * Get language from request Accept-Language header.
 * Supported: fr, en, de. Falls back to 'fr'.
 */
function getLang(req) {
  const header = (req.headers['accept-language'] || '').toLowerCase();
  if (header.startsWith('en')) return 'en';
  if (header.startsWith('de')) return 'de';
  return 'fr';
}

/**
 * Translate a key into the requested language.
 * Interpolates {placeholder} tokens with the `vars` object.
 * Falls back to French if key/lang missing.
 */
function t(lang, key, vars = {}) {
  const entry = MESSAGES[key];
  if (!entry) return key;
  let str = entry[lang] || entry['fr'] || key;
  Object.entries(vars).forEach(([k, v]) => {
    str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
  });
  return str;
}

module.exports = { t, getLang };
